development:
  adapter: postgresql
  encoding: utf8
  database: rdstation_development
  username: thiago
  password: ox1j9ia0
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: rdstation_test
  username: thiago
  password: ox1j9ia0
  host: localhost
